version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: widen
    allow:
      - dependency-name: "*"
        dependency-type: "all"
    groups:
      unit-tests:
        patterns:
          - "phpunit/*"
          - "php-stubs/*"
          - "brain/*"
          - "antecedent/*"
      static-analysis:
        patterns:
          - "nikic/php-parser"
          - "phpstan/*"
          - "szepeviktor/phpstan-wordpress"
      code-style:
        patterns:
          - "yoast/yoastcs"
          - "phpcsstandards/*"
          - "phpcompatibility/*"
          - "squizlabs/*"
          - "slevomat/*"
          - "dealerdirect/phpcodesniffer-composer-installer"
          
